name: SimpleToDo

options:
  deploymentTarget:
    # 元iOS: '15.0'
    iOS: '26.0'

targets:
  SimpleToDo:
    type: application
    platform: iOS

    sources:
      - path: SimpleToDo
        exclude:
          - "Preview Content/**"

    resources:
      - SimpleToDo/Assets.xcassets

    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: SimpleToDo/Info.plist
        #元identifier: com.hackingwithswift.SimpleToDo
        PRODUCT_BUNDLE_IDENTIFIER: jp.taisei.MyApp

        # 👇 重要：未署名前提
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""

        SWIFT_VERSION: 5.0
