name: IOS向けの未署名IPAファイルの生成
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcodeのversion確認
        run: xcodebuild -version

      - name: 初期化
        run: |
          xcodebuild clean \
            -project SimpleToDo/SimpleToDo.xcodeproj \
            -scheme SimpleToDo \
            -configuration Release

      - name: アーカイブ（署名なし）
        run: |
          xcodebuild archive \
            -project SimpleToDo/SimpleToDo.xcodeproj \
            -scheme SimpleToDo \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/SimpleToDo.xcarchive \
            INFOPLIST_FILE=SimpleToDo/Info.plist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: 署名なしIPAの作成
        run: |
          mkdir -p build/ipa/Payload
          cp -R \
            build/SimpleToDo.xcarchive/Products/Applications/SimpleToDo.app \
            build/ipa/Payload/

          cd build/ipa
          zip -r SimpleToDo-unsigned.ipa Payload

      - name: 署名なしIPAのartifactへのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: SimpleToDo-unsigned-ipa
          path: build/ipa/SimpleToDo-unsigned.ipa
